[workspace]
[package]
version = "0.1.0"
name = "fibonacci-benchmark-program"
edition = "2021"

[dependencies]
sp1-zkvm = { path = "../../../zkvm/entrypoint" }

[build-dependencies]
sp1-helper = { path = "../../../helper" }
