[default]
extend-ignore-identifiers-re = [
    # don't fix Groth16
    "(?i).*groth16.*"
]

[default.extend-identifiers]
# don't fix jargon
TwoAdicCase = "TwoAdicCase"

[default.extend-words]
# Don't correct the surname "Wich"
wich = "wich"
# or the acronym TRE
tre =  "tre"
# or the acronym EIN
EIN = "EIN"
