[workspace]
[package]
name = "bls12381-pairing"
version = "0.1.0"
edition = "2021"

[dependencies]
wp1-zkvm = { path = "../../../zkvm/entrypoint" }

#bls12_381 = { path = "../../../../bls12_381" }
bls12_381 = { git = "https://github.com/lurk-lab/bls12_381", branch = "zkvm" }
