[workspace]
[package]
version = "0.1.0"
name = "unnamed-script"
edition = "2021"

[dependencies]
sp1-core = { git = "ssh://git@github.com/wormhole-foundation/wp1.git" }

[build-dependencies]
sp1-helper = { git = "ssh://git@github.com/wormhole-foundation/wp1.git" }