[package]
name = "wp1-zkvm"
version = "0.1.0"
edition = "2021"

[dependencies]
wp1-precompiles = { path = "../precompiles" }
bincode = "1.3.3"
cfg-if = "1.0.0"
getrandom = { version = "0.2.12", features = ["custom"] }
k256 = { version = "0.13.3", features = ["ecdsa", "std", "bits"] }
serde = { version = "1.0.196", features = ["derive"] }
libm = { version = "0.2.8", optional = true }

[target.'cfg(target_os = "zkvm")'.dependencies]
rand = "0.8.5"

[features]
default = ["libm"]
libm = ["dep:libm"]

[package.metadata.cargo-udeps.ignore]
normal = ["libm"]
