[workspace]
[package]
version = "0.1.0"
name = "fibonacci-io-script"
edition = "2021"

[dependencies]
itertools = "0.12.1"
wp1-sdk = { path = "../../../sdk" }
sha2 = "0.10.8"

[build-dependencies]
wp1-helper = { path = "../../../helper" }
