[workspace]
[package]
version = "0.1.0"
name = "io-script"
edition = "2021"

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
wp1-core = { path = "../../../core" }

[build-dependencies]
wp1-helper = { path = "../../../helper" }
