[package]
name = "sp1-recursion-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p3-air = { workspace = true }
p3-field = { workspace = true }
sp1-recursion-core = { path = "../core" }
sp1-core = { path = "../../core" }

[dev-dependencies]
p3-baby-bear = { workspace = true }
rand = "0.8.4"
