# Nightly sanity checks
name: nightly

on:
  workflow_dispatch: {}
  # Once per day at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  unused-dependencies:
    uses: lurk-lab/ci-workflows/.github/workflows/unused-deps.yml@main

  linux-exhaustive:
    name: Run all tests including ignored
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
      - name: Run exhaustive tests
        run: |
          cargo nextest run --cargo-profile dev-ci --profile ci --workspace --run-ignored all -E 'all() - test(test_prove_sp1)'
      - name: Open an issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT: ${{ github.sha }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/templates/NIGHTLY_TESTS.md

  prove:
    name: Prove integration tests and examples
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
      - name: Install `cargo-prove` toolchain
        run: |
          cargo install --locked --path ./cli
          cargo prove install-toolchain
        working-directory: ${{ github.workspace }}
      - name: Prove example scripts
        run: |
          make
          for i in $(find ./ -maxdepth 1 -mindepth 1 -type d); do
            cd "$i/script"
            cargo run --release
            cd ../../
          done
        working-directory: ${{ github.workspace }}/examples
      - name: Build integration tests
        run: make
        working-directory: ${{ github.workspace }}/tests
      - name: Open an issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT: ${{ github.sha }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/NIGHTLY_FAILURE.md
