# Nightly sanity checks
name: nightly

on:
  workflow_dispatch: {}
  # Once per day at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  unused-dependencies:
    uses: lurk-lab/ci-workflows/.github/workflows/unused-deps.yml@main

  rust-version-check:
    uses: lurk-lab/ci-workflows/.github/workflows/rust-version-check.yml@main

  typos:
    uses: lurk-lab/ci-workflows/.github/workflows/typos.yml@main

  prove:
    name: Prove integration tests and examples
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          dirs -c && for i in $(find ./ -depth -type d); do pushd "$i/script"; cargo run --release; popd; done
        working-directory: ${{ github.workspace }}/examples
