name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: CI Test Suite
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
      - name: Run cargo test on wp1 except the prove_sp1 recursion test
        run: |
          cargo nextest run --cargo-profile dev-ci --profile ci --workspace --exclude wp1-recursion-circuit -E 'all() - test(test_prove_sp1)'
      - name: Run cargo test with no default features
        run: |
          cargo nextest run -p wp1-core --cargo-profile dev-ci --profile ci --no-default-features --features debug -- cpu::trace::tests::generate_trace
        working-directory: ${{ github.workspace }}/examples
      - name: Install `cargo prove` CLI
        run: |
          cargo install --locked --path ./cli
          cargo prove install-toolchain
        working-directory: ${{ github.workspace }}
      - name: Run fibonacci-io example
        run: |
          cargo run --release --manifest-path examples/fibonacci-io/script/Cargo.toml

  test-recursion-circuit:
    name: Test recursion circuit
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PRIVATE_PULL_TOEKN }}
      - name: Run cargo test on the recursion circuit
        run: |
          cargo nextest run --cargo-profile dev-ci --profile ci -p wp1-recursion-circuit

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
      - name: Check Rustfmt Code Style
        run: cargo fmt --all --check
      - name: check *everything* compiles
        run: cargo check --all-targets --all-features --all --examples --tests --benches
      # See '.cargo/config' for list of enabled/disabled clippy lints
      - name: Check clippy warnings
        run: cargo xclippy -D warnings
      - name: Doctests
        run: cargo test --doc --workspace
      - name: Cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1

  integration-tests-examples:
    name: Build integration tests and examples
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
          perf: false
      - name: Install `cargo prove` CLI
        run: |
          cargo install --locked --path ./cli
          cargo prove install-toolchain
        working-directory: ${{ github.workspace }}
      - name: Check examples
        run: |
          for i in $(find ./ -maxdepth 1 -mindepth 1 -type d); do
            cd "$i/script"
            cargo check
            cd ../../
          done
        working-directory: ${{ github.workspace }}/examples
      - name: Check integration tests
        run: |
          for i in $(find ./ -maxdepth 1 -mindepth 1 -type d); do
            cd "$i"
            cargo check
            cd ../
          done
        working-directory: ${{ github.workspace }}/tests
      - name: Run cargo prove new
        run: |
          cargo prove new cargo-prove-test
          cd cargo-prove-test
          cd script
          cargo run --release


  mac-m1:
    name: CI Tests on OSX ARM
    runs-on: macos-latest-xlarge
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
      - name: Run cargo test on wp1 except the prove_sp1 recursion test
        run: |
          cargo nextest run --cargo-profile dev-ci --profile ci -E 'all() - test(test_prove_sp1)'
      - name: Run cargo test with no default features
        run: |
          cargo nextest run -p wp1-core --cargo-profile dev-ci --profile ci --no-default-features --features debug -- cpu::trace::tests::generate_trace
      - name: check examples compile
        run: |
          for i in $(find ./ -maxdepth 1 -mindepth 1 -type d); do
            cd "$i/script"
            cargo check
            cd ../../
          done
        working-directory: ${{ github.workspace }}/examples
      - name: Set env
        if: failure()
        run: |
          echo "WORKFLOW_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" | tee -a $GITHUB_ENV
      - name: Open an issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT: ${{ github.sha }}
          WORKFLOW_URL: ${{ env.WORKFLOW_URL }}
        with:
          filename: .github/M1_MAC_FAILURE.md
          update_existing: true

  check-aptos-lc-compiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
          path: ci-workflows
      - uses: ./ci-workflows/.github/actions/ci-env
      - uses: ./ci-workflows/.github/actions/install-deps
        with:
          packages: "pkg-config libudev-dev"
      - name: Set env
        run: |
          echo "DOWNSTREAM_REPO=$(echo "wormhole-foundation/example-zk-light-clients-internal" | awk -F'/' '{ print $2 }')" | tee -a $GITHUB_ENV
          echo "UPSTREAM_REPO=$(echo "wormhole-foundation/wp1" | awk -F'/' '{ print $2 }')" | tee -a $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/${{ env.UPSTREAM_REPO }}
          submodules: recursive
      - name: Install cargo prove
        run: |
          cargo install --locked --path .
          cargo prove install-toolchain
        working-directory: ${{ github.workspace }}/${{ env.UPSTREAM_REPO }}/cli
      - name: Setup CI
        uses: ./wp1/.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
          perf: false
      - name: Install WP1 toolchain
        run: |
          cd wp1/cli
          cargo install --locked --path .
          cd ~
          cargo prove install-toolchain
      - uses: actions/checkout@v4
        with:
          repository: "wormhole-foundation/${{ env.DOWNSTREAM_REPO }}"
          path: ${{ github.workspace }}/${{ env.DOWNSTREAM_REPO }}
          token: ${{ secrets.REPO_TOKEN }}
          submodules: recursive
      - uses: ./ci-workflows/.github/actions/check-downstream-compiles
        with:
          upstream-path: "${{ env.UPSTREAM_REPO }}"
          downstream-path: "${{ env.DOWNSTREAM_REPO }}/aptos"
          patch-ssh: true

  # TEMPORARY: Test on PR
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install typos binary
        run: cargo +stable install typos-cli
      - name: Check typos
        uses: crate-ci/typos@v1
