name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "core/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: CI Test Suite
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - name: Set env
        run: |
          echo "RUSTFLAGS=${{env.RUSTFLAGS}} -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0" | tee -a $GITHUB_ENV
          echo "RUST_LOG=1" | tee -a $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@nextest
      - name: Run cargo test on sp1-core
        run: |
          cargo nextest run -p sp1-core --release --profile ci
      - name: Run cargo test on sp1-recursion-compiler
        run: |
          cargo nextest run -p sp1-recursion-compiler --release --profile ci
      - name: Run cargo test with no default features
        run: |
          cargo nextest run -p sp1-core --release --profile ci --no-default-features --features debug -- cpu::trace::tests::generate_trace

  # Rustfmt, clippy, doctests
  code-quality:
    uses: lurk-lab/ci-workflows/.github/workflows/lints.yml@main
