name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: CI Test Suite
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}
      - name: Run cargo test on wp1 except the prove_sp1 recursion test
        run: |
          cargo nextest run --cargo-profile dev-ci --profile ci -E 'all() - test(test_prove_sp1)'
      - name: Run cargo test with no default features
        run: |
          cargo nextest run -p wp1-core --cargo-profile dev-ci --profile ci --no-default-features --features debug -- cpu::trace::tests::generate_trace
        working-directory: ${{ github.workspace }}/examples
      - name: Run fibonacci-io example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --manifest-path examples/fibonacci-io/script/Cargo.toml
  

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}
      - name: Check Rustfmt Code Style
        run: cargo fmt --all --check
      - name: check *everything* compiles
        run: cargo check --all-targets --all-features --all --examples --tests --benches
      # See '.cargo/config' for list of enabled/disabled clippy lints
      - name: Check clippy warnings
        run: cargo xclippy -D warnings
      - name: Doctests
        run: cargo test --doc --workspace
      - name: Cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1

  integration-tests-examples:
    name: Build integration tests and examples
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}
      - name: Install `cargo prove` CLI
        run: |
          cargo install --locked --path ./cli
          cargo prove install-toolchain
        working-directory: ${{ github.workspace }}
      - name: Check examples
        run: |
          for i in $(find ./ -maxdepth 1 -mindepth 1 -type d); do
            cd "$i/script"
            cargo check
            cd ../../
          done
        working-directory: ${{ github.workspace }}/examples
      - name: Check integration tests
        run: |
          for i in $(find ./ -maxdepth 1 -mindepth 1 -type d); do
            cd "$i"
            cargo check
            cd ../
          done
        working-directory: ${{ github.workspace }}/tests

  mac-m1:
    name: CI Tests on OSX ARM
    runs-on: macos-latest-xlarge
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}
      - name: Run cargo test on wp1 except the prove_sp1 recursion test
        run: |
          cargo nextest run --cargo-profile dev-ci --profile ci -E 'all() - test(test_prove_sp1)'
      - name: Run cargo test with no default features
        run: |
          cargo nextest run -p wp1-core --cargo-profile dev-ci --profile ci --no-default-features --features debug -- cpu::trace::tests::generate_trace
      - name: check examples compile
        run: |
          for i in $(find ./ -maxdepth 1 -mindepth 1 -type d); do
            cd "$i/script"
            cargo check
            cd ../../
          done
        working-directory: ${{ github.workspace }}/examples
      - name: Set env
        if: failure()
        run: |
          echo "WORKFLOW_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" | tee -a $GITHUB_ENV
      - name: Open an issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT: ${{ github.sha }}
          WORKFLOW_URL: ${{ env.WORKFLOW_URL }}
        with:
          filename: .github/M1_MAC_FAILURE.md
          update_existing: true
