name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: CI Test Suite
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - name: Set env
        run: |
          echo "RUSTFLAGS=${{env.RUSTFLAGS}} -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0" | tee -a $GITHUB_ENV
          echo "RUST_LOG=1" | tee -a $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@nextest
      - name: Run cargo test on wp1-core
        run: |
          cargo nextest run -p wp1-core --release --profile ci
      - name: Run cargo test on wp1-recursion-compiler, wp1-recursion-program, wp1-recursion-circuit
        run: |
          cargo nextest run -p wp1-recursion-compiler -p wp1-recursion-program -p wp1-recursion-circuit --release --profile ci
      - name: Run cargo test with no default features
        run: |
          cargo nextest run -p wp1-core --release --profile ci --no-default-features --features debug -- cpu::trace::tests::generate_trace

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Check Rustfmt Code Style
        run: cargo fmt --all --check
      # See '.cargo/config' for list of enabled/disabled clippy lints
      - name: Check clippy warnings
        run: cargo xclippy -D warnings
      - name: Doctests
        run: cargo test --doc --workspace
